name: linux

on:
    push:

jobs:
    build-linux:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-20.04]

        steps:
            - uses: actions/checkout@v1
            - name: setup
              run: |
                  sudo apt update
                  sudo apt install gcc-10 g++-10
                  cd ../..
                  git clone https://github.com/open-ephys/plugin-GUI.git --branch main
                  sudo ./plugin-GUI/Resources/Scripts/install_linux_dependencies.sh
                  cd plugin-GUI/Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
              env:
                  CC: gcc-10
                  CXX: g++-10
            - name: build
              run: |
                  git submodule update --init
                  cd Build
                  cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
                  cmake --build .
              env:
                  CC: gcc-10
                  CXX: g++-10
            #    - name: test
            #      run: cd build && ctest
            - name: deploy
              if: github.ref == 'refs/heads/xdaq_dev'
              env:
                  #        artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
                  build_dir: "Build"
                  package: XDAQ-OE-linux
              run: |
                  plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]*" | tail -1)
                  tag=$(git describe --tags $(git rev-list --tags --max-count=1))
                  new_plugin_ver=$tag-API$plugin_api
                  mkdir plugins 
                  cp -r $build_dir/*.so plugins
                  mkdir shared	
                  cp third_party/FrontPanel/libokFrontPanel.so shared
                  zipfile=${package}_${new_plugin_ver}.zip
                  zip -r -X $zipfile plugins shared
              # curl -H "X-JFrog-Art-Api:$artifactoryApiKey" -T $zipfile "https://openephys.jfrog.io/artifactory/RhythmPlugins-plugin/linux/$zipfile"
